# Dock: Create a docker image containing tools and programs required
#   to run VHDL simulations.

# Use existing image for GHDLS
FROM ghdl/ghdl:ubuntu22-mcode

# LABEL about the custom image
LABEL maintainer="Chase Ruskin"
LABEL description="GHDL mcode build for Ubuntu 22.04"

# Enter the shell
CMD ["bash"]